### ISSUE TITLE
Broken Link?

### ISSUE THREAD

**Issue by JustinDCole** [sayantanm19/js-music-player#1]
I worked on the same project by using your source code. When I pulled up the final html file on the browser, all the elements were positioned in the top left corner. 

There's no picture, even though I saved the jpg files I wanted to use properly. Plus the two sliders don't work in unison, and you have to drag the time-slider. No music plays, which is the most important part. 

Is the link for the icons wrong bc when I pulled it up, there was nothing but plain code. 
I don't know what's wrong.

![Screenshot (32)](https://user-images.githubusercontent.com/64715169/95204240-ce7f7f00-07b1-11eb-8b01-93a874e42812.png)

![Screenshot (31)](https://user-images.githubusercontent.com/64715169/95204248-d3443300-07b1-11eb-87c0-b608d4e6b308.png)

**Comment by sayantanm19** [comment]
The icons are shown using FontAwesome, so as long as you have the link to its CDN included and have used the necessary tags, it should work. Please verify that the style CSS file is accessible from the HTML for the styling to be properly shown.

Also, according to the second image, you have not correctly written the <meta> tag as the syntax highlighting below that is not correct. You can clone this project and check where you might have made the mistake, as it works fine on my end.

**Comment by JustinDCole** [comment]
How should I write it?

**Comment by sayantanm19** [comment]
As of the error I can see, you can remove the whole meta tag, or copy it correctly from an online source. It seems you are missing some double quotes in one of the properties of the meta tag.
