### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by MegaTKC** [sayantanm19/js-music-player#3]
I have an issue. How do you add more songs? I tried adding more of this: `{
    name: "Shipping Lanes",
    artist: "Chad Crouch",
    image: "Image URL",
    path: "Shipping_Lanes.mp3",
  },`

It didn't work though. It still said 3 songs. Can you try to help me please?

**Comment by sayantanm19** [comment]
Are you sure you have added the track details in the same format with all the fields? Each of the object will represent one track, separated by a single comma. The details of the song would update automatically based on the length of the tracks array.

**Comment by MegaTKC** [comment]
Thanks for helping me. I just did something wrong in the code. I just tried it again and it worked. It showed 1 of 4. Thanks.
